language: node_js
node_js:
  14
cache:
  directories:
    - node_modules
    - ~/.npm
git:
  depth: 3
script:
  - yarn build
notifications:
  email:
    recipients:
      - lesterpaz99@gmail.com
      - 1180268@usap.edu
    on_success: always
    on_failure: always
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: dist/
  target_branch: gh-pages
  commit_message: "Deploy de proyecto"
  on:
    branch: main